api:
  dashboard: false
  debug: false

entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: "3600s"
        writeTimeout: "3600s"
        idleTimeout: "3600s"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "3600s"
        writeTimeout: "3600s"
        idleTimeout: "3600s"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{email}}"
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true